MODULE params
	PARAMETER (IQX=370, IPX=5, ISX=2)
	PARAMETER (IWX=IQX/8+2)
	PARAMETER (IBX=4*IQX)
	PARAMETER (IZX=IQX+IWX)
	PARAMETER (IVX=IQX/2 + IWX + 50)
	PARAMETER (NAX=800,NPX=12,NFX=128)
	PARAMETER (NTX=2*IBX)
	!REAL::CVPAR,CTERAT,CTRRAT
	!REAL :: ALFA 
	!integer :: NPAN = 160,N
	!NPAN = 160
END MODULE params
